import Link from "next/link";
import { getFilmRepository } from "@/lib/data";
import type { Film } from "@/lib/types";

export const dynamic = "force-dynamic";

export const metadata = { title: "Collections" };

// Hand-curated shelves — each defined by a cinematic quality, not a genre.
// (Static ids for now; later these could be computed from the corpus or
// generated by the exploration engine.)
const COLLECTIONS: { name: string; desc: string; ids: string[] }[] = [
  {
    name: "Slow-burn dread",
    desc: "Tension that accumulates instead of erupting. No jump scares required.",
    ids: [
      "the-witch-2015",
      "the-lighthouse-2019",
      "possum-2018",
      "picnic-at-hanging-rock-1975",
      "enemy-2013",
    ],
  },
  {
    name: "Meditative sci-fi",
    desc: "The cosmos as an interior space — patient, philosophical, near-wordless.",
    ids: [
      "stalker-1979",
      "solaris-1972",
      "2001-a-space-odyssey-1968",
      "blade-runner-2049-2017",
      "under-the-skin-2013",
    ],
  },
  {
    name: "Neon loneliness",
    desc: "Cities after dark and the people who stay awake in them.",
    ids: [
      "lost-in-translation-2003",
      "drive-2011",
      "nightcrawler-2014",
      "in-the-mood-for-love-2000",
      "blade-runner-2049-2017",
    ],
  },
  {
    name: "Unresolved",
    desc: "Mysteries that withhold their answers — the ambiguity is the point.",
    ids: [
      "picnic-at-hanging-rock-1975",
      "zodiac-2007",
      "annihilation-2018",
      "enemy-2013",
      "the-thing-1982",
    ],
  },
];

export default async function CollectionsPage() {
  const catalog = await getFilmRepository().listFilms();
  const byId = new Map(catalog.map((f) => [f.id, f]));

  return (
    <div className="pt-16">
      <p className="text-[11px] tracking-[0.35em] uppercase text-[#e0632f] mb-4">
        Collections
      </p>
      <h1 className="font-display text-4xl md:text-5xl mb-3">
        Shelves by <em className="text-[#e0632f]">feeling.</em>
      </h1>
      <p className="text-[#8f8b82] max-w-xl mb-14 text-sm leading-relaxed">
        Curated groupings by cinematic quality rather than genre — the same
        idea the search engine uses, assembled by hand.
      </p>

      <div className="space-y-14">
        {COLLECTIONS.map((c) => (
          <section key={c.name}>
            <h2 className="font-display text-2xl mb-1.5">{c.name}</h2>
            <p className="text-sm text-[#8f8b82] mb-5">{c.desc}</p>
            <div className="flex flex-wrap gap-3">
              {c.ids
                .map((id) => byId.get(id))
                .filter((f): f is Film => !!f)
                .map((f) => (
                  <Link
                    key={f.id}
                    href={`/film/${f.id}`}
                    className="rounded-full border border-[#2a2825] bg-[#141315] px-4 py-2 text-sm text-[#b7b2a7] hover:border-[#e0632f] hover:text-[#e0632f] transition-colors"
                  >
                    {f.metadata.title}
                    <span className="ml-1.5 text-[#6b675f]">
                      {f.metadata.year}
                    </span>
                  </Link>
                ))}
            </div>
          </section>
        ))}
      </div>
    </div>
  );
}
